"""add university

Revision ID: 5b57ba9507dd
Revises: b2e8f1a94c3d
Create Date: 2026-07-17 00:18:05.310397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b57ba9507dd'
down_revision: Union[str, Sequence[str], None] = 'b2e8f1a94c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('incentive_slabs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incentive_slabs_id'), 'incentive_slabs', ['id'], unique=False)
    op.add_column('prospects', sa.Column('university', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('monthly_sales_target', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'monthly_sales_target')
    op.drop_column('prospects', 'university')
    op.drop_index(op.f('ix_incentive_slabs_id'), table_name='incentive_slabs')
    op.drop_table('incentive_slabs')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
